<a href="https://colab.research.google.com/github/Simranjit16/Machine-learning/blob/SML/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy

In [0]:
import numpy as np

In [0]:
a=np.array([2,7,1,99,4])

In [0]:
type(a)

numpy.ndarray

In [0]:
b=np.array([12,17,199,11,14])

In [0]:
a

array([ 2,  7,  1, 99,  4])

In [0]:
b

array([ 12,  17, 199,  11,  14])

In [0]:
a[2]

1

In [0]:
b[3]

11

In [0]:
a+b

array([ 14,  24, 200, 110,  18])

In [0]:
a+2

array([  4,   9,   3, 101,   6])

In [0]:
a*2

array([  4,  14,   2, 198,   8])

In [0]:
a**2

array([   4,   49,    1, 9801,   16])

In [0]:
c=a+b

In [0]:
print(c)


[ 14  24 200 110  18]


In [0]:
a5=a+5

In [0]:
print(a5)

[  7  12   6 104   9]


In [0]:
x=np.array([[2,5,8],[3,6,1]])

In [0]:
x

array([[2, 5, 8],
       [3, 6, 1]])

In [0]:
x[0][0]

2

In [0]:
x[1][2]

1

In [0]:
x[1]

array([3, 6, 1])

In [0]:
x+7

array([[ 9, 12, 15],
       [10, 13,  8]])

In [0]:
x[1]+7

array([10, 13,  8])

In [0]:
z=np.array([[2,7],[3,8],[2,9],[9,4]])

In [0]:
z

array([[2, 7],
       [3, 8],
       [2, 9],
       [9, 4]])

In [0]:
z.shape

(4, 2)

In [0]:
x.shape


(2, 3)

In [0]:
x

array([[2, 5, 8],
       [3, 6, 1]])

In [0]:
z

array([[2, 7],
       [3, 8],
       [2, 9],
       [9, 4]])

In [0]:
z[0]

array([2, 7])

In [0]:
z[0:2]

array([[2, 7],
       [3, 8]])

In [0]:
z[0:]


array([[2, 7],
       [3, 8],
       [2, 9],
       [9, 4]])

In [0]:
z[0: ,]

array([[2, 7],
       [3, 8],
       [2, 9],
       [9, 4]])

In [0]:
z[0:,0]

array([2, 3, 2, 9])

In [0]:
z[0:2,0]

array([2, 3])

In [0]:
z[0:,1]

array([7, 8, 9, 4])

In [0]:
z[0:,0:2]

array([[2, 7],
       [3, 8],
       [2, 9],
       [9, 4]])

In [0]:
z[[0,3]]

array([[2, 7],
       [9, 4]])

In [0]:
z[1:,0]


array([3, 2, 9])

In [0]:
z

array([[2, 7],
       [3, 8],
       [2, 9],
       [9, 4]])

In [0]:
b=np.array([[1,9,7],[3,2,8],[4,5,6],[2,9,0]])

In [0]:
b[0:,1]

array([9, 2, 5, 9])

In [0]:
b[0:,2]

array([7, 8, 6, 0])

In [0]:
b[1:3,1]

array([2, 5])

In [0]:
b[1:4,2]

array([8, 6, 0])

In [0]:
b[1:,[0,2]]

array([[3, 8],
       [4, 6],
       [2, 0]])

In [0]:
x

array([[2, 5, 8],
       [3, 6, 1]])

In [0]:
x.shape

(2, 3)

In [0]:
x.reshape(3,2)

array([[2, 5],
       [8, 3],
       [6, 1]])

In [0]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [0]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [0]:
np.full((4,5),9)

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

In [0]:
for i in dir(np):
  if 'zer' in i:
    print(i)

count_nonzero
flatnonzero
nonzero
trim_zeros
zeros
zeros_like


In [0]:
import numpy as np
import random
x=np.arange(6).reshape(3,2)
y=np.arange(10).reshape(2,5)
for i in range(3):
    for j in range(2):
        x[i][j]=random.randint(1,10)
for i in range(2):
    for j in range(5):
        y[i][j]=random.randint(1,20)

print("Saving following data into  the file :")
print(x)
print(y)
#Saving into files
np.savetxt("thtw.csv",x,delimiter=",")
np.savetxt("twfi.csv",y,delimiter=",")


#reading data From Files
data=np.genfromtxt('thtw.csv',delimiter=',')
data1=np.genfromtxt('twfi.csv',delimiter=',')
print("Reading Data from file and Reshape it :")
print(data.reshape(2,3))
print(data1.reshape(5,2))


Saving following data into  the file :
[[10  5]
 [10  6]
 [ 3  3]]
[[ 1 10 20 10 17]
 [11  2 15 20  8]]
Reading Data from file and Reshape it :
[[10.  5. 10.]
 [ 6.  3.  3.]]
[[ 1. 10.]
 [20. 10.]
 [17. 11.]
 [ 2. 15.]
 [20.  8.]]


enter the dimensions of first array3 2
enter the dimensions of second array5 2


In [0]:
print(x)

[[41 17]
 [54 89]
 [95 94]]


In [0]:
print(y)

[[43 29]
 [ 2 65]
 [84 98]
 [47 82]
 [98 89]]


In [0]:
print(x)

[[41 17]
 [54 89]
 [95 94]]
